### PR TITLE
Fix similar titles for menu items

### PR DESCRIPTION
**Pull request by ghiath-dev**
Adding key for the menu item to unique the items when same title is used.

While using your package and when adding items which having same title i noticed the following problems:

- The similar items show once for the model menu panel.
- Adding the item will add all the similar items to the menu.

I fixed it by:
1.  Adding unique "key" column and attribute for the menu items to handle the difference.
2. Add "getMenuPanelKeyColumn" function in the HasMenuPanel and HasMenuPanel Contracts.
3. Modify the MenuPanel.php to form the items with key => title 
4. Filter items when adding by the new key column in ModelMenuPanel.php.

Hope i explained the issue and the fix clearly.

At the end, Thanks for sharing the package, It was useful.

### CODE REVIEW

**Comment by datlechin** [comment]
Does it break the existing app?

**Comment by ghiath-dev** [comment]
Sorry, I didn't understand what you mean?

It was not a break problem, but as i explained
- The similar items show once for the model menu panel.
- Adding the item will add all the similar items to the menu.

**Comment by datlechin** [comment]
We may need write migration to generate key for existing menu items

**Comment by ghiath-dev** [comment]
I see.

So separate migration for adding the key column.

**Pull request closed without merging**
