### PR TITLE
Add ability to add text only items. (#47)

### LINKED ISSUE #47: [Request]: Add a custom text-only item
_As the discussions are disabled there isn't another avenue to post feature requests currently, so apologies for having to go through this channel._

I currently need to add an item to the menu that is text only, as sort of a label. The item I need to add is different from the title of the parent item. It would currently be possible to add a custom URL with target of `#` and then manually changing the the display of said item to be title only, however this is a little confusing for the users to configure. It would be great to have a simple way to add a custom item to the menu that is not a custom link.

Here's what I would love to accomplish in a mega menu setup:

```
Home
Men            <-- Doesn't need to be a link since this is a mega menu
  Categories   <-- Not a link, text only
    Shirts
    Pants
  Brands       <-- Not a link, text only
    Brand 1
    Brand 2
```

As mentioned, there currently is a solution to this, which would be to create a custom URL called "Categories" with a URL set to `#` and then manually handling the situation in the view. It would just be easier to understand if it had a dedicated action, which I don't see a way to achieve currently.

### PR DESCRIPTION
**Pull request by Senexis**
Closes #47 

This adds a panel that allows users to add an item that is text only without having to enter a URL or select a target.

I shouldn't have forgotten anything, but please give it a once-over. :)

### CODE REVIEW

**Comment by Senexis** [comment]
I have updated it to disable the panel by default, as well as adding documentation, where you can see how to enable it as well as a short explainer and example.

**Comment by Senexis** [comment]
Looking over it again, it may be a good idea to rename the methods and variable to include `Panel`:

`showCustomLink` -> `showCustomLinkPanel`
`showCustomText` -> `showCustomTextPanel`

A bit of a derp, what do you think?

**Comment by datlechin** [comment]
> Looking over it again, it may be a good idea to rename the methods and variable to include `Panel`:
> 
> `showCustomLink` -> `showCustomLinkPanel` `showCustomText` -> `showCustomTextPanel`
> 
> A bit of a derp, what do you think?

Yes, it sounds good, change it also please

**Comment by Senexis** [comment]
Already did! :)

**Review by datlechin — APPROVED** [review]
Thank you!

**Pull request merged**
